### ISSUE TITLE
Return cmd output on error

### ISSUE THREAD

**Issue by stevanmilic** [roerohan/wait-for-it#7]
Hi, thanks for this nice utility!

Is it possible to exit the `wait-for-it` program with error exit code in case underlying command returns an error? Doing so would indicate the command we were waiting for has failed, and that we need to address it somehow. 

I can submit a PR for this, if this is acceptable behavior.

**Comment by stevanmilic** [comment]
@roerohan I've made a PR for this https://github.com/roerohan/wait-for-it/pull/8, please take a look when you got the time, thanks!

**Comment by roerohan** [comment]
Hi @stevanmilic 

Thanks for contributing! I'll take a look at the PR and leave a review (and get it merged as well!)
